config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  
  get 'set_language/english'
  get 'set_language/czech'
  
  resources :switch_rooms, only: [:index, :create, :destroy, :new] do 
    post "accept", on: :member
  end
  resources :not_running, only: [:index]
  resources :app_settings, only: [:index, :update] do 
    post "send_welcome_mails", on: :collection
    post "send_apollogize_mails", on: :collection
  end

  resources :alliance_membership_requests, only: [:create, :destroy] do 
    post "accept", on: :member
  end

  resources :places, path: 'reservations', only: [:index, :edit, :update] do 
    post 'reservations/create'
    post 'reservations/create_for_alliance', on: :collection
    delete 'reservations/destroy'
  end

  resources :aliances do 
    post "remove_member", on: :member
  end
  
  devise_for :users, path: '', only: [:sessions, :password]

  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: :authenticated_root
    end
  
    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end


  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'dashboard#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/views/shared/header/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <a class="navbar-brand" href="/"><%=t("header.appname")%></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <% if current_user %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <%= render "shared/header/header_admin_links" if current_user.admin %>
                <%= render "shared/header/header_student_links" if !current_user.admin %>
            </ul>
            <ul class="navbar-nav">

                <div class="form-inline">
                    <%if I18n.locale == :en %>
                        <%= link_to "Česky", set_language_czech_path, class: "btn btn-outline-primary" %>
                    <% else %>
                        <%= link_to "English", set_language_english_path, class: "btn btn-outline-primary" %>
                    <% end %>
                </div>
                <li class="nav-item">
                    <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-link') %>            
                </li>
            </ul>
        </div>
    <% end %>
</nav>
  
  

app/views/shared/header/_header_admin_links.html.erb
<li class="nav-item <%= 'active' if controller_name == "dashboard" %>">
    <%= link_to "/", class: "nav-link"  do %> <%=t("header.home") %> <%end %>
</li>
<li class="nav-item <%= 'active' if controller_name == "users" %>">
    <%= link_to t("header.users"), users_path, class: "nav-link" %>
</li>
<li class="nav-item <%= 'active' if controller_name == "places" %>">
    <%= link_to t("header.reservations"), places_path, class: "nav-link" %>
</li>
<li class="nav-item <%= 'active' if controller_name == "app_settings" %>">
    <%= link_to t("header.app_settings"), app_settings_path, class: "nav-link" %>
</li>

app/views/shared/header/_header_student_links.html.erb
<li class="nav-item active">
    <a class="nav-link" href="/"><%=t("header.home")%><span class="sr-only">(current)</span></a>
</li>
<li class="nav-item <%= 'active' if controller_name == "places" %>">
    <%= link_to t("header.reservations"), places_path, class: "nav-link" %>
</li>
<li class="nav-item <%= 'active' if controller_name == "users" %>">
    <%= link_to t("header.profile"), edit_user_path(current_user), class: "nav-link" %>
</li>
<li class="nav-item <%= 'active' if controller_name == "aliances" %>">
    <%= link_to t("header.alliance"), aliances_path, class: "nav-link" %>
</li>
<li class="nav-item <%= 'active' if controller_name == "switch_rooms" %>">
    <%= link_to t("header.switch_rooms"), switch_rooms_path, class: "nav-link" %>
</li>

    