config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  
  get 'set_language/english'
  get 'set_language/czech'
  
  resources :switch_rooms, only: [:index, :create, :destroy, :new] do 
    post "accept", on: :member
  end
  resources :not_running, only: [:index]
  resources :app_settings, only: [:index, :update] do 
    post "send_welcome_mails", on: :collection
    post "send_apollogize_mails", on: :collection
  end

  resources :alliance_membership_requests, only: [:create, :destroy] do 
    post "accept", on: :member
  end

  resources :places, path: 'reservations', only: [:index, :edit, :update] do 
    post 'reservations/create'
    post 'reservations/create_for_alliance', on: :collection
    delete 'reservations/destroy'
  end

  resources :aliances do 
    post "remove_member", on: :member
  end
  
  devise_for :users, path: '', only: [:sessions, :password]

  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: :authenticated_root
    end
  
    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end


  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'dashboard#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/aliance.rb
class Aliance < ApplicationRecord
  belongs_to :founder, class_name: :User
  has_many :users, dependent: :nullify
  has_many :alliance_membership_requests, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/controllers/aliances_controller.rb
class AliancesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_aliance, only: [:edit, :update, :destroy]

  # GET /aliances
  # GET /aliances.json
  def index
    
    redirect_to aliance_path(current_user.aliance) if current_user.aliance 
    redirect_to aliance_path(current_user.alliance_membership_request.aliance) if current_user.alliance_membership_request
    
    @aliances = Aliance.all
  end

  # GET /aliances/1
  # GET /aliances/1.json
  def show
    @aliance = Aliance.includes(:alliance_membership_requests).find(params[:id])
    unauthorized unless (current_user.aliance == @aliance || current_user.pending_alliance == @aliance)
  end

  # GET /aliances/new
  def new
    @aliance = Aliance.new()
  end

  # GET /aliances/1/edit
  def edit
    unauthorized unless @aliance.founder == current_user
  end

  # POST /aliances
  # POST /aliances.json
  def create
    @aliance = Aliance.new(aliance_params)
    @aliance.founder = current_user
    @aliance.users.push(current_user)

    respond_to do |format|
      if @aliance.save
        format.html { redirect_to @aliance, notice: 'Aliance was successfully created.' }
        format.json { render :show, status: :created, location: @aliance }
      else
        format.html { render :new }
        format.json { render json: @aliance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aliances/1
  # PATCH/PUT /aliances/1.json
  def update
    respond_to do |format|
      if @aliance.update(aliance_params)
        format.html { redirect_to @aliance, notice: 'Aliance was successfully updated.' }
        format.json { render :show, status: :ok, location: @aliance }
      else
        format.html { render :edit }
        format.json { render json: @aliance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aliances/1
  # DELETE /aliances/1.json
  def destroy
    @aliance.destroy
    respond_to do |format|
      format.html { redirect_to aliances_url, notice: 'Aliance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_member 
    removed_user = User.find(params[:user_id])
    if current_user.aliance == removed_user.aliance 
      removed_user.aliance = nil
      if removed_user.save 
        respond_to do |format|
          format.html { redirect_to aliances_url, notice: 'Member successfullly removed' }
        end
      else
        respond_to do |format|
          format.html { redirect_to aliances_url, error: 'Error during member removal' }
        end
      end
    else 
      respond_to do |format|
        format.html { redirect_to aliances_url, alert: 'You must be member of the same aliance as user' }
        format.json { head :no_content }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aliance
      @aliance = Aliance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aliance_params
      params.require(:aliance).permit(:name, :note)
    end
end

app/helpers/aliances_helper.rb
module AliancesHelper
end

app/views/aliances/_form.html.erb
<%= form_with(model: aliance, local: true) do |form| %>
  
  <%= render "shared/errors", object: aliance %>
  
  <div class="form-group">
    <%= form.label t("alliance.name")+" "+t("general.public") %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label t("alliance.founder") %>
    <input name="founder-placeholder" class="form-control" disabled="true" value="<%=current_user.fullname %>">
  </div>

  <div class="form-group">
    <%= form.label t("alliance.description")+" "+t("general.public") %>
    <%= form.text_area :note, class: "form-control" %>
  </div>

  <div class="d-flex justify-content-between">
    <%= link_to t("general.cancel"), aliances_path, class: "btn btn-outline-secondary" %>
    <%= form.submit t("general.submit"),class: "btn btn-primary" %>
  </div>
<% end %>

app/views/aliances/edit.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-6 col-lg-4">
            <h1><%=t("alliance.editing")%></h1>

            <%= render 'form', aliance: @aliance %>
        
        </div>
    </div>
</div>

app/views/aliances/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">

      <h1><%=t("alliance.alliance")%></h1>
      <p>
      <%=t("alliance.purpose_info")%>
      </p>

       <hr>
        <p><%=t("alliance.you_can_join")%></p>
        <p><%=t("alliance.you_can_also")%>
          <div class="text-center">
            <%= link_to t("alliance.create"), new_aliance_path, class:"btn btn-success btn-lg" %>
          </div>
        </p>
        <table class="table table-striped">
          <thead>
            <tr>
              <th><%=t("alliance.name")%></th>
              <th><%=t("alliance.description")%></th>
              <th colspan="2"></th>
            </tr>
          </thead>

          <tbody>
            <% @aliances.each do |aliance| %>
              <tr>
                <td><%= aliance.name %></td>
                <td><%= aliance.note %></td>
                <td><%= link_to t("alliance.join"), alliance_membership_requests_path(aliance_id:  aliance.id), method: :post, class: "btn btn-primary" if current_user.aliance.nil? %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/aliances/new.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-6 col-lg-4">
        
            <h1><%=t("alliance.creation")%></h1>

            <%= render 'form', aliance: @aliance %>
        
        </div>
    </div>
</div>

app/views/aliances/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 mb-4">
      <div class="card">
        <div class="card-header">
          <%=t("alliance.alliance") %>
        </div>
        <table class="table mb-0">
          <tbody>
            <tr><td><strong><%=t("alliance.name")%></strong></td><td><%= @aliance.name %></td></tr>
            <tr><td><strong><%=t("alliance.description")%></strong></td> <td><%= @aliance.note %></td> </tr>
            <% if @aliance.founder == current_user %>
              <tr>
                <td colspan="2" class="text-center">
                  <%= link_to t("alliance.edit"), edit_aliance_path(@aliance), class: "btn btn-warning"  %>
                  <%= link_to t("alliance.destroy"), @aliance, method: :delete, data: {confirm: t("alliance.destroy_confirmation")}, class: "btn btn-danger"  %>
                </td> 
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <% if current_user.pending_alliance %>
    <!-- START pending request to alliance -->
    <div class="col-md-6">
      <div class="alert alert-warning">
	<%= t("alliance.pending_request_info")%>
        <%= link_to t("alliance.cancel_request"), 
            alliance_membership_request_path(current_user.alliance_membership_request), 
            method: :delete, 
            data: {confirm: t("alliance.cancel_request_confirm")},
            class: "btn btn-danger mt-2"
        %> 
      </div>
    </div>
    <!-- END pending request to alliance -->
    <% else %>
    <!-- START inside alliance -->
    <div class="col-md-6">
      <div class="card">
        <div class="card-header"><%=t("alliance.members")%></div>
        <div class="table-responsive">
          <table class="table mb-0">
            <thead><th><%=t("alliance.member_name")%></th><th><%=t("activerecord.attributes.user.email")%></th><th></th></thead>
            <tbody>
              <% @aliance.users.each do |user| %>
                <tr>
                  <td><%= user.fullname %></td>
                  <td><%= user.email %></td>
                  <td>
                    <% unless user == @aliance.founder %>
                      <%= link_to t("alliance.remove_member"), 
                          remove_member_aliance_path(@aliance, {user_id: user.id }), 
                          method: :post,
                          class: "btn btn-danger" 
                      %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>

      <div class="card mt-4">
        <div class="card-header"><%=t("alliance.requests")%></div>
        <% if @aliance.alliance_membership_requests.blank? %>
          <div class="card-body">
            <%=t("alliance.no_requests")%>
          </div>
        <% else %>
          <div class="table-responsive">
            <table class="table mb-0">
              <thead><th><%=t("alliance.member_name")%></th><th><%=t("activerecord.attributes.user.email")%></th><th colspan="2"></th></thead>
              <tbody>
                <% @aliance.alliance_membership_requests.each do |membership| %>
                  <tr>
                    <td><%= membership.user.fullname %></td>
                    <td><%= membership.user.email %></td>
                    <td><%= link_to t("alliance.accept"), accept_alliance_membership_request_path(membership), class:"btn btn-primary", method: :post %> </td>
                    <td><%= link_to t("alliance.dismiss"), membership, method: :delete, class:"btn btn-danger" %> </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
      </div>

    </div>
    <!-- END inside alliance -->
    <% end %>
  </div>
</div>