config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  
  get 'set_language/english'
  get 'set_language/czech'
  
  resources :switch_rooms, only: [:index, :create, :destroy, :new] do 
    post "accept", on: :member
  end
  resources :not_running, only: [:index]
  resources :app_settings, only: [:index, :update] do 
    post "send_welcome_mails", on: :collection
    post "send_apollogize_mails", on: :collection
  end

  resources :alliance_membership_requests, only: [:create, :destroy] do 
    post "accept", on: :member
  end

  resources :places, path: 'reservations', only: [:index, :edit, :update] do 
    post 'reservations/create'
    post 'reservations/create_for_alliance', on: :collection
    delete 'reservations/destroy'
  end

  resources :aliances do 
    post "remove_member", on: :member
  end
  
  devise_for :users, path: '', only: [:sessions, :password]

  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: :authenticated_root
    end
  
    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end


  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'dashboard#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/alliance_membership_request.rb
class AllianceMembershipRequest < ApplicationRecord
  belongs_to :user
  belongs_to :aliance
end

app/controllers/alliance_membership_requests_controller.rb
class AllianceMembershipRequestsController < ApplicationController

  # POST /alliance_membership_requests
  # POST /alliance_membership_requests.json
  def create
    @alliance_membership_request = AllianceMembershipRequest.new(alliance_membership_request_params)
    @alliance_membership_request.user = current_user
    respond_to do |format|
      if @alliance_membership_request.save
        format.html { redirect_to aliances_path, notice: 'Alliance membership request was successfully created.' }
      else
        format.html { redirect_to aliances_path, alert: 'Error occured. Try it again please.' }
      end
    end
  end

  # DELETE /alliance_membership_requests/1
  # DELETE /alliance_membership_requests/1.json
  def destroy
    @alliance_membership_request = AllianceMembershipRequest.find(params[:id])
    @alliance_membership_request.destroy
    respond_to do |format|
      format.html { redirect_to aliances_path, notice: 'Alliance membership request was successfully cancelled.' }
    end
  end

  def accept
    @alliance_membership_request = AllianceMembershipRequest.find(params[:id])
    @alliance_membership_request.user.aliance = @alliance_membership_request.aliance
    @alliance_membership_request.user.save!
    @alliance_membership_request.destroy!
    
    respond_to do |format|
      format.html { redirect_to aliances_path, notice: 'Alliance membership request was successfully accepted.' }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def alliance_membership_request_params
      params.permit(:user_id, :aliance_id)
    end
end

app/helpers/alliance_membership_requests_helper.rb
module AllianceMembershipRequestsHelper
end

app/views/alliance_membership_requests/_form.html.erb
<%= form_with(model: alliance_membership_request, local: true) do |form| %>
  <%= render "shared/errors", object: alliance_membership_request %>


  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :alliance_id %>
    <%= form.text_field :alliance_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alliance_membership_requests/edit.html.erb
<h1>Editing Alliance Membership Request</h1>

<%= render 'form', alliance_membership_request: @alliance_membership_request %>

<%= link_to 'Show', @alliance_membership_request %> |
<%= link_to 'Back', alliance_membership_requests_path %>

app/views/alliance_membership_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alliance Membership Requests</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Alliance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alliance_membership_requests.each do |alliance_membership_request| %>
      <tr>
        <td><%= alliance_membership_request.user %></td>
        <td><%= alliance_membership_request.alliance %></td>
        <td><%= link_to 'Show', alliance_membership_request %></td>
        <td><%= link_to 'Edit', edit_alliance_membership_request_path(alliance_membership_request) %></td>
        <td><%= link_to 'Destroy', alliance_membership_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alliance Membership Request', new_alliance_membership_request_path %>

app/views/alliance_membership_requests/new.html.erb
<h1>New Alliance Membership Request</h1>

<%= render 'form', alliance_membership_request: @alliance_membership_request %>

<%= link_to 'Back', alliance_membership_requests_path %>

app/views/alliance_membership_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @alliance_membership_request.user %>
</p>

<p>
  <strong>Alliance:</strong>
  <%= @alliance_membership_request.alliance %>
</p>

<%= link_to 'Edit', edit_alliance_membership_request_path(@alliance_membership_request) %> |
<%= link_to 'Back', alliance_membership_requests_path %>