config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  
  get 'set_language/english'
  get 'set_language/czech'
  
  resources :switch_rooms, only: [:index, :create, :destroy, :new] do 
    post "accept", on: :member
  end
  resources :not_running, only: [:index]
  resources :app_settings, only: [:index, :update] do 
    post "send_welcome_mails", on: :collection
    post "send_apollogize_mails", on: :collection
  end

  resources :alliance_membership_requests, only: [:create, :destroy] do 
    post "accept", on: :member
  end

  resources :places, path: 'reservations', only: [:index, :edit, :update] do 
    post 'reservations/create'
    post 'reservations/create_for_alliance', on: :collection
    delete 'reservations/destroy'
  end

  resources :aliances do 
    post "remove_member", on: :member
  end
  
  devise_for :users, path: '', only: [:sessions, :password]

  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: :authenticated_root
    end
  
    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end


  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'dashboard#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :primary_claim, class_name: :User, optional: true
  belongs_to :secondary_claim, class_name: :User, optional: true
  belongs_to :admin_claim, class_name: :User, optional: true
  validates  :user, :secondary_claim, :primary_claim, uniqueness: true, allow_nil: true

  validate :sex_validation, :room_type_validation
  validate :round_validation

  after_commit :remove_user_switch_place_requests
  
  has_paper_trail only: [:user]


  scope :places_not_colliding_with_restriction, ->(current_user) do 
    # no place on same cell/room with user having same sex as in parameter
    query = "NOT EXISTS (
      SELECT 1 AS one
      FROM places as inner_places INNER JOIN users ON users.id = inner_places.user_id 
      WHERE   places.id != inner_places.id "
    query += " AND users.male != ?"
    query += " AND places.cell = inner_places.cell" if current_user.same_sex_cell
    query += " AND places.cell = inner_places.cell AND places.room = inner_places.room" if !current_user.same_sex_cell && current_user.same_sex_room
    query += ")"

    # no place on same cell/room with user having same sex as in parameter
    query_not_collide_with_existing_reservations = "NOT EXISTS(
      SELECT 1 AS one
      FROM places as inner_places INNER JOIN users on users.id = inner_places.user_id
      WHERE users.male != ? AND (
            (users.same_sex_cell AND inner_places.cell = places.cell) OR
            (users.same_sex_room AND places.cell = inner_places.cell AND places.room = inner_places.room)
          )
    )"
    res = where(query_not_collide_with_existing_reservations, current_user.male)
    res = res.where(query, current_user.male) if current_user.same_sex_cell || current_user.same_sex_room
    res
  end

  scope :available, -> (current_user) do
    where(user_id: nil).places_not_colliding_with_restriction(current_user)
  end

  def available?(current_user)
    return false unless self.user.nil? 
    return available_eventhough_could_be_full?(current_user)
  end

  def available_for_switch_with?(user)
    return !user.place.nil? &&
           user.place != self &&
           !self.user.nil? &&
           user.switch_room_requests_made.where.not(user_requested_id: self.user.id).size == 0 &&
           user.switch_room_requests_incoming.where.not(user_requested_id: self.user.id).size == 0 &&
           available_eventhough_could_be_full?(user)
  end

  def availability_status(current_user)
    return :unavailable_reserved if !self.user.nil?
    return :unavailable_wrong_type if self.room_type != current_user.room_type
    return :unavailable_round if !self.correct_round?(current_user)
    return :unavailable_different_sex if !self.available?(current_user)
    return :available
  end

  def places_on_same_room
    return Place.where(building: self.building, floor: self.floor, room: self.room).where.not(id: self.id).preload(:user)
  end

  def places_on_same_cell
    return Place.where(building: self.building, floor: self.floor, cell: self.cell).where.not(id: self.id).preload(:user)
  end

  def self.places_count(current_user, building, floor = nil, cell = nil)
    places = self.where(building: building)
    places = places.where(floor: floor) if floor
    places = places.where(cell: cell) if cell
    Rails.cache.fetch(places.available(current_user).cache_key) do
      count = PlacesCount.new(places.available(current_user).count, places.count)
      count
    end
  end


  def name 
    return self.room + "#" + self.bed
  end

  
  def room_name 
    self.room
  end

  def correct_round?(current_user)
    if self.admin_claim == current_user
      return true 
    elsif AppSetting.first.current_round == :fourth
       return true
    elsif  current_user.secondary_claim && AppSetting.first.current_round_numeric > 1 && current_user.secondary_claim.room_name == self.room_name
       return true
    elsif  current_user.primary_claim && AppSetting.first.current_round_numeric > 0 && current_user.primary_claim.room_name == self.room_name
       return true
    else
       return false
    end 
  end

  private 


  def available_eventhough_could_be_full?(current_user) 
    return false unless self.room_type == current_user.room_type

    ## Is place valid if we move user in ##
    place_orig_user = self.user
    self.user = current_user
    is_valid = self.valid? 
    # hotfix - unique place validation per user
    is_valid = true if self.errors.count == 1 && self.errors.first && self.errors.first.include?(:user)

    self.user = place_orig_user
    return is_valid
  end


  ###
  ### Validations
  ###  

  def sex_validation
    if self.user 
      res = 
      # not violating mine preferences
      (!self.user.same_sex_cell || places_on_same_cell.all? {|place| place.user.nil? || place.user.male == self.user.male}) &&
      (!self.user.same_sex_room || places_on_same_room.all? {|place| place.user.nil? || place.user.male == self.user.male}) &&
      # not violationg others preferences
      places_on_same_cell.all? {|place| place.user.nil? || !place.user.same_sex_cell || place.user.male == self.user.male } &&
      places_on_same_room.all? {|place| place.user.nil? || !place.user.same_sex_room || place.user.male == self.user.male }
      
      self.errors.add(:sex, I18n.t("general.sex.mismatch")) unless res
      res
    else 
      true
    end
  end

  def round_validation
    if !self.user.nil? && !self.correct_round?(self.user)
      self.errors.add(:round, "You do not have right to reserve this room in this round")
      return false
    else
      true
    end
  end

  def room_type_validation
    if !self.user.nil? && self.room_type != self.user.room_type
      self.errors.add(:room_type, "Wrong type of room")
      return false
    else
      true
    end
  end

  #
  # Callbacks
  #

  def remove_user_switch_place_requests 
    self.user.switch_room_requests_made.destroy_all if self.user
    self.user.switch_room_requests_incoming.destroy_all if self.user
  end


end

class PlacesCount
  attr_reader :free, :all

  def initialize(free, all)
    @free = free 
    @all = all
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  # GET /places
  # GET /places.json
  def index
    @params = params.permit(:building, :floor)
    
    @buildings = Place.distinct.pluck(:building)
    @floors = Place.where(building:params[:building]).distinct.order(:floor).pluck(:floor) if @params[:building]
    @current_user_place = current_user.place
    if @params[:building] && @params[:floor]
      @cells = Place.where(building: @params[:building], floor: @params[:floor]).order(:room, :id).includes(:user).group_by{|i| i.cell}
    end
  end

  # GET /places/1/edit
  def edit
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    admin_only
    
    respond_to do |format|
      params = place_params
      params = params.except(:room_type) if params[:room_type] == ""
      params[:user_id] = nil if params[:user_id] == ""
      
      
      orig_place = Place.find_by(user_id: params[:user_id])
      orig_place&.update(user: nil, admin_claim: nil)
      
      @place.admin_claim_id = params[:user_id]

      if @place.update(params)
        format.html { redirect_to places_path, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      return params.require(:place).permit(:room_type, :user_id) if current_user.admin?
      return params.require(:place).permit() unless current_user.admin?
    end
end

app/helpers/places_helper.rb
module PlacesHelper
    def room_full(place)
        return place.name
    end

    def free_spaces_count_class(places_count)
        ratio = places_count.free.to_f/places_count.all

        if ratio > 0.5 
            'success'
        elsif ratio > 0
            'warning'
        else 
            'danger'
        end
    end
end

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>

  <%= render "shared/errors", object: place %>

  <div class="form-group">
    <%= form.label :room_type %>
    <%= form.text_field :room_type, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label t("reservation.guest") %>
    <%= form.text_field :user_id, class: "form-control" %>
  </div>

  <div class="actions">
    <%= link_to 'Back', :back, class: "btn btn-outline-secondary" %>
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/places/_places_count.html.erb
<span class="badge badge-light"> 
    <span class="text-<%= free_spaces_count_class(places_count) %>">
        <%= places_count.free %> / <%= places_count.all %>
    </span>
</span>

app/views/places/edit.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-6 col-lg-4">
        
        <h1><%=t("reservation.edit_bed") %></h1>

        <%= render 'form', place: @place %>
        
        </div>
    </div>
</div>

app/views/places/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1><%=t("reservation.reservation")%></h1>

      <% if @current_user_place and !current_user.admin%>
        <div class="alert alert-success" role="alert">
          <%=t("reservation.existing_reservation")%> <%= room_full @current_user_place %>.
        </div>
      <% elsif !current_user.admin %>
        <div class="alert alert-warning" role="alert">
          <%=t("reservation.no_reservation")%>
        </div>
      <% end %>
    </div>
    <div class="col-12">
      <div class="card">
        <div class="card-header">Select place</div>
        <div class="card-body">
          <div class="mb-3">
            <%=t("reservation.building")%>:
            <% for building in @buildings do %>
              <%= link_to(
                    @params.merge(building: building), 
                    {class: "btn btn#{'-outline' unless @params[:building] == building}-info mb-2"}
                  ) do 
              %>
                <%= building %>
                <%= render partial: "places_count", locals: {places_count: Place.places_count(current_user, building)} %>
              <% end %>
            <% end %>
          </div>
          <% if @params[:building] %>
            <div>
              <%=t("reservation.floor")%>: 
              <% for floor in @floors do %>
                <%= link_to( 
                      @params.merge(floor: floor), 
                      class: "btn btn#{'-outline' if @params[:floor].nil? || @params[:floor].to_i != floor}-info mb-2"
                    ) do
                %>
                  <%= floor %>
                  <%= render partial: "places_count", locals: {places_count: Place.places_count(current_user, @params[:building], floor.to_s)} %>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% if @cells %>
  <div class="row">
    <div class="col-12">
      <h1><%=t("reservation.cells")%></h1>
      <div class="row">

        <% @cells.each do |cell, places| %>
          <div class="col-lg-4 col-sm-6">
            <div class="card mb-4">
              <h5 class="card-header"><%= cell %>
                  <%= render partial: "places_count", locals: {places_count: Place.places_count(current_user, @params[:building], @params[:floor], cell)} %>
                  <% if  !current_user.admin? && (AppSetting.first.current_round == :fourth or @current_user_place && AppSetting.first.current_round == :third && @current_user_place.cell.to_s == cell.to_s)%>
                    
                    <%= link_to t("reservation.move_alliance"), 
                        reservations_create_for_alliance_places_path(aliance_id: current_user.aliance.id, cell: cell), 
                        class: "btn btn-success",
                        method: :post if current_user.aliance
                    %>
                  <% end %>
              </h5>
              <ul class="list-group list-group-flush">
                <% places.each do |place| %>
                  <li class="list-group-item">
                    <strong> <%= link_to_if current_user.admin?, place.name, edit_place_path(place) %> </strong>
                    <!-- USER -->
                    <% if !current_user.admin %>
                      <!-- available -->
                      <% if place.available?(current_user) %> 
                        <%= link_to t("reservation.reserve"), 
                            place_reservations_create_path(place_id: place.id), 
                            class: "btn btn-success",
                            method: :post,
                            data: @current_user_place.nil? ? nil : {confirm: t("reservation.existing_reservation")+" #{room_full(@current_user_place)}. "+ t("reservation.confirm_change") } 
                        %>

                      <!-- reserved by me -->                     
                      <% elsif place.user === current_user %>
                        <%= link_to t("reservation.cancel"), 
                            place_reservations_destroy_path(place_id: place.id), 
                            class: "btn btn-warning",
                            method: :delete,
                            data: { confirm: t("reservation.confirm_cancel") }
                        %>

                      <!-- wrong round -->               
                      <% elsif place.availability_status(current_user) == :unavailable_round %>
                        <%= button_tag t("reservation.wrong_round"), 
                          class: "btn btn-danger",
                          disabled: true %>

                      <!-- wrong room type -->                     
                      <% elsif place.availability_status(current_user) == :unavailable_wrong_type %>
                        <%= button_tag t("reservation.wrong_type"),  
                            class: "btn btn-danger",
                            disabled: true 
                        %>
                      <!-- not matching sex -->                  
                      <% elsif place.availability_status(current_user) == :unavailable_different_sex %>
                        <%= button_tag t("reservation.wrong_sex"), 
                            class: "btn btn-danger",
                            disabled: true %>
                      <!-- reserved by someone else -->
                      <% else %>
                          <%= button_tag t("reservation.taken_" + (place.user.male ? "male" : "female")), 
                            class: "btn btn-danger",
                            disabled: true %>
                          <% if false && !@current_user_place.nil? and current_user.switch_room_requests_made.size === 0%>
                              <%= link_to t("reservation.send_switch_room_request"), new_switch_room_path({place_id: place.id}), class: 'btn btn-info' %>
                          <% end %>
                      <% end %>

                      <% if !current_user.aliance_id.nil? && current_user.aliance_id == place.user&.aliance_id && current_user != place.user %>
                        <br>
                        <%= t("reservation.here_lives") %>: <%= place.user&.fullname %> 
                      <% end %>

                    <!-- ADMIN -->
                    <% else %>
                    <%= link_to t("general.edit"), edit_place_path(place), class:"btn btn-primary" %>
                      <br>
                      bydlí: 
                      <% if place.user %>
                        <%= link_to place.user.fullname, edit_user_path(place.user) %>;
                        <% if place.user.same_sex_cell %> 
                          Na buňce pouze
                        <% elsif place.user.same_sex_room %>
                          Na pokoj pouze
                        <% end %>
                        <%= place.user.male ? "muž" : "žena"%>;
                      <% else %>
                        Volno
                      <% end %>

                      
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

</div>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Building:</strong>
  <%= @place.building %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @place.floor %>
</p>

<p>
  <strong>Cell:</strong>
  <%= @place.cell %>
</p>

<p>
  <strong>Room:</strong>
  <%= @place.room %>
</p>

<p>
  <strong>Bed:</strong>
  <%= @place.bed %>
</p>

<p>
  <strong>User:</strong>
  <%= @place.user %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>